version: '3'
services:
  kong-database:
    image: postgres:9.6
    ports:
      - 5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
  kong:
    image: kong:latest
    env_file:
      - ./kong.env
    volumes:
      - ./migrate.sh:/migrate.sh
    ports: 
      - 8000:8000
    depends_on: 
      - kong-database
    command: sh -c "chmod u+x /migrate.sh && /migrate.sh && /docker-entrypoint.sh kong docker-start"
